name: Build

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build test container
      run: docker build -t bemidb-test -f Dockerfile.test --build-arg PLATFORM=linux/amd64 .

    - name: Run tests
      run: docker run --rm bemidb-test
